Add abstract
NLnetLabs/draft-koekkoek-dnsop-zone-file-format pull request #2
Opened 2023-04-25 08:43 UTC by k0ekk0ek

Add an initial abstract that outlines the goals of the Internet-Draft.

2023-04-26 08:23 UTC, partim reviewed
I probably wouldn’t mention the RFC breaking grammar. Varying dialects should be enough of a reason.

How about something like this for the goal: “This document aims to establish a common, well-defined base line for zone files that can be understood by all implementations.”

2023-04-26 09:08 UTC, k0ekk0ek commented
That's better wording indeed. Will change it :+1:

2023-05-16 14:18 UTC, wtoorop requested changes

2023-05-16 14:18 UTC, wtoorop commented on draft-koekkoek-dnsop-zone-file-format.md
> +directly.
This doesn't read nicely for me

2023-05-16 14:18 UTC, wtoorop commented on draft-koekkoek-dnsop-zone-file-format.md
> +Notice that [@!RFC1034] and [@!RFC1035] define three adjacent text formats
```suggestion
[@!RFC1034] and [@!RFC1035] define three adjacent text formats
```

2023-05-16 14:18 UTC, wtoorop commented on draft-koekkoek-dnsop-zone-file-format.md
> +master file to define a zone are clearly defined too.
```suggestion
RFCs that introduce new (RR) TYPEs document the textual representation of the TYPEs specific RDATA,
together with the restrictions that apply when used to define a zone in a master file.
```

2023-05-16 14:18 UTC, wtoorop commented on draft-koekkoek-dnsop-zone-file-format.md
> +the master file format defines a forward compatible syntax for expressing RRs.
```suggestion
The master file format defines a forward compatible syntax for expressing RRs.
```

2023-05-16 14:18 UTC, wtoorop commented on draft-koekkoek-dnsop-zone-file-format.md
> +and different dialects based on the readers background.
```suggestion
The format has provisions for easier editing by text editor, but
clearly defined semantics around these provisions are lacking.
This has led to different interpretations of the format in implementations.
```

2023-05-16 14:18 UTC, wtoorop commented on draft-koekkoek-dnsop-zone-file-format.md
> +This document clarifies and formalizes syntax and semantics.
```suggestion
This document clarifies and formalizes syntax and semantics, to align implementations and increase interoperability.
```

2023-05-16 14:22 UTC, wtoorop commented on draft-koekkoek-dnsop-zone-file-format.md
> +directly.
```suggestion
```

2023-07-06 08:44 UTC, partim commented on draft-koekkoek-dnsop-zone-file-format.md
> +FIXME: The term master files is inconvenient, perhaps we should come up with
It occurs to me that the term is also wrong – it would _only_ be a master file if it contains the zone definition for a primary. If it lists the content of a cache (as given as an example in 1035), it decidedly isn’t a “master” any more. So, if it is a master file, it also is a zonefile. Otherwise it is only a file containing a list of records.

2023-07-06 08:46 UTC, partim commented on draft-koekkoek-dnsop-zone-file-format.md
> +implementations that intend to be compliant. This document redefines the
I still think – at least at this stage – stating a goal of “providing a minimum profile of the presentation format that guarantees interoperability” (or somesuch) is better than just plain wanting to redefine it.

2023-07-06 08:50 UTC, partim commented on draft-koekkoek-dnsop-zone-file-format.md
> +       The exception here being SVCB, which is mostly already accepted. We do
I don’t think it is a good idea to try to open the discussion about the SVCB presentation format again. However, you might want to look at the ABNF given for character strings in this draft – I think it is incorrect, but it could serve as a starting point.

2023-07-06 09:06 UTC, k0ekk0ek commented on draft-koekkoek-dnsop-zone-file-format.md
> +       The exception here being SVCB, which is mostly already accepted. We do
We're not looking to change anything regarding SVCB, rather we're trying to keep future RFCs from using inconvenient syntax for RDATA fields. `foo="bar"` would be two separate tokens, which we can work with still, but if someone comes up with something really creative that would break the lexers in BIND (I think, they use a separate lexer too), NSD and simdzone. Possibly others. Often times it's not required to break it, I think people simply are not aware(?) We intend to specify the preferred syntax and then list SVCB as the exception.

2023-07-06 09:17 UTC, k0ekk0ek commented on draft-koekkoek-dnsop-zone-file-format.md
> +FIXME: The term master files is inconvenient, perhaps we should come up with
I agree. RFC1035 even specifies it as a text file containing a set of RRs. In my understanding, there is only a slight difference in textual expression of RRs and the format in master files (directives). Maybe we should just formally combine the two and stick with presentation format. That's the practical solution to the problem(?) The term is also already defined as such in the terminology draft.

2023-07-06 09:17 UTC, partim commented on draft-koekkoek-dnsop-zone-file-format.md
> +       The exception here being SVCB, which is mostly already accepted. We do
I suspect there might be more records that will use a key/value pair format a la SVCB. It might be worthwhile to define the SVCB format as the standard for all of those?

2023-07-06 09:19 UTC, partim commented on draft-koekkoek-dnsop-zone-file-format.md
> +FIXME: The term master files is inconvenient, perhaps we should come up with
Makes sense: Presentation format for record data and presentation format for a set of records.

2023-07-06 09:26 UTC, k0ekk0ek commented on draft-koekkoek-dnsop-zone-file-format.md
> +implementations that intend to be compliant. This document redefines the
I think we're on the same page. The intend is to outline how things should be interpreted by means of specifying syntax and semantics first. Then try to determine where we can be lenient (i.e. should vs. must). The problem with the format is that it's too ambiguous, so reaching consensus on what it should be ideally is a sensible approach?

2023-07-17 23:25 UTC, shane-kerr reviewed
I think this is an awesome next step for this document. I've thrown some comments in the PR.

2023-07-17 23:25 UTC, shane-kerr commented on draft-koekkoek-dnsop-zone-file-format.md
> +       The exception here being SVCB, which is mostly already accepted. We do
Anything to reduce innovation in type formats would be welcome, although I suspect futile. :wink: 

I guess it is worth noting that future RDATA types that want to use key/value pairs and really want the `foo=bar` syntax that they should re-use the SVCB/HTTPS syntax.

2023-07-17 23:25 UTC, shane-kerr commented on draft-koekkoek-dnsop-zone-file-format.md
> +FIXME: Evaluate for inclusion: https://datatracker.ietf.org/doc/html/rfc2181#section-8
Worthwhile including, although the language here indicates that it is about bits on the wire, and does not offer help to implementers reading zone files that violate this.

2023-07-17 23:25 UTC, shane-kerr commented on draft-koekkoek-dnsop-zone-file-format.md
> +FIXME: Evaluate for inclusion: https://www.rfc-editor.org/rfc/rfc8767#section-4
Wow the text there breaks my brain a little. Makes sense though... treating TTL as 0 is probably always a bad idea. :wink: 

Based on the stale RFC, my own suggestion would be something like:

"Any software reading a zone file that encounters a TTL more than 2^31 - 1 SHOULD reduce the TTL to 2^31 -1 or consider the RR an error."

This should be okay with DNSSEC, since TTL a reduced TTL is okay AFAIK.

Probably a section (elsewhere I guess) on how to handle errors is reasonable, for example. Nothing super complex, but good to list options.

2023-07-17 23:25 UTC, shane-kerr commented on draft-koekkoek-dnsop-zone-file-format.md
> +FIXME: Evaluate for inclusion: https://github.com/NLnetLabs/ldns/commit/cb101c9
For me the only interesting issue there is that there is a corner case where the first record (an SOA in a zone file, but we're considering other textual representations using RR) does not have a TTL listed. I generally treat this as an error, although I guess there might be some other approach.

2023-07-17 23:25 UTC, shane-kerr commented on draft-koekkoek-dnsop-zone-file-format.md
> +FIXME: Consider https://github.com/NLnetLabs/simdzone/blob/main/FORMAT.md
We'll need to address most of those points eventually. :laughing:

2023-07-18 18:42 UTC, k0ekk0ek commented on draft-koekkoek-dnsop-zone-file-format.md
> +FIXME: The term master files is inconvenient, perhaps we should come up with
Updated. Included a section. Still need to remove the term from other places in the document (except terminology), but we'll get there :+1:

2023-07-18 18:43 UTC, k0ekk0ek commented on draft-koekkoek-dnsop-zone-file-format.md
> +implementations that intend to be compliant. This document redefines the
I think it's fixed, but we can refine it after merging the initial text.

2023-07-18 18:43 UTC, k0ekk0ek commented on draft-koekkoek-dnsop-zone-file-format.md
> +       The exception here being SVCB, which is mostly already accepted. We do
@shane-kerr, I suspect you're right. I've included your remark. We'll refine later.

2023-07-18 18:43 UTC, k0ekk0ek commented on draft-koekkoek-dnsop-zone-file-format.md
> +       master files?
Fixed

2023-07-18 18:44 UTC, k0ekk0ek commented on draft-koekkoek-dnsop-zone-file-format.md
> +[@!RFC3597] externs the format to allow for generic notation of RDATA.
Fixed

2023-07-18 18:45 UTC, k0ekk0ek commented
That's the initial text. Let's refine! PRs welcome :smile:

2023-07-18 18:45 UTC, merged